#  menu items
#[[main]]
#  name = "Drivers"
#  weight = 2
#  url = "drivers/"

[[main]]
  name = "About"
  weight = 5
  url = "about/"

[[main]]
  name = "Free Prevention"
  weight = 6
  url = "https://www.magicsword.io/plan?utm_source=loldrivers&utm_medium=website&utm_campaign=free_prevention&utm_content=nav_menu"
