name: Publish a Release 
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python 3.11
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.11
    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python -
    - name: Install dependencies with Poetry
      run: poetry install
    - name: Run YAML Checks
      run: poetry run python bin/validate.py -v

  create_release:
    needs: validate-yaml
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        lfs: true
  
    - name: Build drivers.zip
      run: |
        mkdir -p build/metadata
        mkdir -p build/drivers
        cp -r yaml/ build/metadata
        cp -r drivers/ build/drivers
        cd build
        zip -r drivers.zip metadata/ drivers/
  
    - name: Create Release and Upload drivers.zip
      uses: softprops/action-gh-release@v1
      with:
        files: build/drivers.zip
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
        
        

